try
{
    hello();
}
catch(error)
{
    console.log(error);
}

try
{
    anotherFuction();
}
catch
{
    console.log('Esto es un error');
}